### ISSUE TITLE
太感谢了！

### ISSUE THREAD

**Issue by 99kg** [hteen/apple-store-helper#11]
成功的抢到了两部12pm 感谢！！！！！！！！！！！

**Comment by joooay** [comment]
怎么用啊？？？！！！！！

**Comment by 99kg** [comment]
> 怎么用啊？？？！！！！！

软件里说明作者写的挺清楚啦，先获取那个注册码，然后监控你的预约店就行啦，有货就能自动打开浏览器，你下单就好了。

**Comment by 99kg** [comment]
> 怎么用啊？？？！！！！！

你要是早上6点能起来的话建议你电脑打开北京时间，手机打开预约界面，提前复制好你的身份证号，05：59：59点开那个链接进去抢就好了。

**Comment by joooay** [comment]
好的谢谢~我之前是想问这个软件怎么下来着，因为压缩包解压不成功，但是现在好啦，我是准备6点的，但是我的APPLE STORE软件不好用有bug,所以只能用网页，但是这个网页注册码又很费时间，非常麻烦。所以现在也不知道该怎么办了。。。。


| |
周杰
|
|
15064437751@163.com
|
签名由网易邮箱大师定制
在2020年11月16日 09:49，象牙山王大拿<notifications@github.com> 写道：

怎么用啊？？？！！！！！

你要是早上6点能起来的话建议你电脑打开北京时间，手机打开预约界面，提前复制好你的身份证号，05：59：59点开那个链接进去抢就好了。
