### ISSUE TITLE
关于“添加澳门地区支持”的一个错误

### ISSUE THREAD

**Issue by XchaDali** [hteen/apple-store-helper#12]
您好 我有澳门地区预约的需求 所以在之前曾下载过您的源码进行修改 以添加澳门地区预约支持 
在今天发现您提交新版本后发现您已经添加了支持 但粗略阅读代码后发现如下错误：
“skuUrl := "https://reserve-prime.apple.com/"+area+"/reserve/"+modelCode[md]+"/availability.json" 
这条代码中获取澳门地区库存情况 理论上来说是无法获取到正确结果的 原因是Apple澳门官网的url是“apple.com/mo” 所以正确的代码应该是：
“skuUrl := "https://reserve-prime.apple.com/MO/zh_MO/reserve/"+modelCode[md]+"/availability.json" 
且由于澳门版/港版型号不同 所有型号末尾的ZH/A应为ZA/A
由于提出该issue时Apple预约服务器已关闭 且您修改后的支持澳门区预约的版本没有提供源码 故本issue是否真实存在并未经验证 如明日经实际测试后没有问题 我会自行关闭该issue
由于本人没有学习过编程所以措辞可能有些问题 见谅。

**Comment by XchaDali** [comment]
经测试确实无法正常使用。无法获取正确的存货信息

**Comment by hteen** [comment]
skuUrl没错, area需要在打包时修改 Line:96

```golang 
var area = "MO/zh_MO"
```

型号末尾的ZH/A的确错误

**Comment by XchaDali** [comment]
在打包时修改Line:96 且将所有CH/A改为ZA/A后 仍然出现无法正确获取库存的情况 问题与issue#13 所提到的相似 以有库存的iPhone 12为例 打包后获取注册码仍然存在“所有门店无货”的情况

**Comment by hteen** [comment]
@XchaDali 最新代码已经修复, 不过我的 macOS 升级 Big Sur打不起包了😂

**Comment by XchaDali** [comment]
感谢🙏 因为这个问题在当时我修改自己的代码的时候 也出现了 没有解决方法 提交这个issue更多是想向您请教一下😅 我也是Big Sur系统 打包是正常的

**Comment by hteen** [comment]
1.0.5版 已修复澳门地区BUG
