### ISSUE TITLE
澳門預約存在問題

### ISSUE THREAD

**Issue by deepfish** [hteen/apple-store-helper#13]
不好意思，昨晚看到你的回覆，今天試了一下，發現有 2 個問題：
1.嘗試使用 iPhone 12 進行預約看看工具是否功能正常，但是發現 Apple 官網上 iPhone 12 能正常預約（https://reserve-prime.apple.com/MO/zh_MO/reserve/F/availability?iUP=N ），但是程序上卻提示無貨；

![](https://i.imgur.com/y6u4bSP.png)

2.門店的選擇的時候有些中文字符無法顯示。

![](https://i.imgur.com/Pe9mFi9.png)

**Comment by hteen** [comment]
Duplicate of #12
