### ISSUE TITLE
早上六点场的必购码没法提前获取吧？

### ISSUE THREAD

**Issue by fengmikaelson** [hteen/apple-store-helper#14]
这几天早上6点起来预约，都来不及。

上库存了，再去弄必购码，复制手机，手机发短信，再返回给电脑。。。好难呀。

而且白天补货的话，也不懂什么时候补，必购码又30分钟有效。补货再临时发必购码的话又来不及了。。。

弄的头疼

**Comment by hteen** [comment]
可以使用底部 “获取注册码” 按钮提前获取对应机型注册码, 前提是需要任意一个门店有货才可以

**Comment by fengmikaelson** [comment]
> 可以使用底部 “获取注册码” 按钮提前获取对应机型注册码, 前提是需要任意一个门店有货才可以

是呀，早上6点前那会儿所有门店都没货了= =获取注册码点了也没反应。那看来注册码只能准时获取了。
不过监控白天的补货倒是挺有用的。要是运气好，拿到注册码的话，刚好30分钟有补货，那就舒服了。
