### ISSUE TITLE
澳门门店的监听有问题

### ISSUE THREAD

**Issue by baijincaomei** [hteen/apple-store-helper#19]
澳门门店明明有货 软件监听提示无货

**Comment by hteen** [comment]
> 澳门门店明明有货 软件监听提示无货

是1.0.5版吗, 最好贴上截图

**Comment by baijincaomei** [comment]
是1.05版 现在澳门门店没货了 但是一直开着监听也没提示有货

**Comment by baijincaomei** [comment]
![1](https://user-images.githubusercontent.com/22868894/103263376-ab482280-49e2-11eb-9715-6fb90e3644b6.jpg)

**Comment by hteen** [comment]
每秒监听请求一次库存, 理论上是有空档期, 正好进入页面显示有货

**Comment by baijincaomei** [comment]
澳门门店有货至少持续了有十来分钟 但是监听一直提示无货

**Comment by baijincaomei** [comment]
![1](https://user-images.githubusercontent.com/22868894/103323159-81433e80-4a7c-11eb-90d9-70e29b4047c1.png)
![2](https://user-images.githubusercontent.com/22868894/103323163-886a4c80-4a7c-11eb-9540-05e3f3032b5d.png)
图来了
