### ISSUE TITLE
考虑更新一下iPhone13的吗~

### ISSUE THREAD

**Issue by Geek-Mao** [hteen/apple-store-helper#20]

**Comment by hteen** [comment]
等官网支持预定到店了, 有空的话会更新

**Comment by Geek-Mao** [comment]
我试着改了一下 型号什么的好像已经可以看到了 比如13p的蓝色是MLTJ3CH/A。但是目前不确定modelCode是不是还是H，F，A，G，再加上预约页面没开。没法儿测试。
