### ISSUE TITLE
测试监控可预约的库存 显示无货

### ISSUE THREAD

**Issue by googooog** [hteen/apple-store-helper#25]
测试了几个零售店可以预约的库存，软件都显示无货，是不是预约端口变了，请求更新，谢谢

**Comment by Ehustein** [comment]
同样的问题，有货依然显示无货

**Comment by w526433357** [comment]
同样的问题，apple store当天可预约的型号，软件显示无货

**Comment by hteen** [comment]
目前库存接口无效, apple今年改变了预约到店流程和接口, 之后版本修复

**Comment by ilee2go** [comment]
问题确实存在！！！亲测，手动选择有货（随便选择iphone 13）软件显示无货~是不是因为今年是可以预约今天、明天、后天，才导致的呢？

**Comment by wenyang94** [comment]
目前不可用，promax根本抢不到，有黄牛。。

**Comment by hteen** [comment]
1.3.2 修复
