### ISSUE TITLE
能否增加香港地区?

### ISSUE THREAD

**Issue by oscarother** [hteen/apple-store-helper#26]
能否增加香港地区?

**Comment by hteen** [comment]
香港地区库存接口没有找到 😂

**Comment by oscarother** [comment]
我有, 你看看是不是这一条link?
https://www.apple.com//hk/shop/retail/pickup-message?pl=true&parts.0=MLHL3ZA/A&location=hongkong
    Hteen ***@***.***>) 在 2021年9月26日星期日 下午01:38:36 [GMT+8] 寫道：  
 
 


香港地区库存接口没有找到 😂
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
