### ISSUE TITLE
打开 iphone12pro 预购地址是错误的

### ISSUE THREAD

**Issue by BlackHole1** [hteen/apple-store-helper#3]
目前代码中如果发现存在iphone12 pro，则会打开一个url地址，代码如下：

```go
url = "https://reserve-prime.apple.com/CN/zh_CN/reserve/A?quantity=1&anchor-store="+params[0]+
	"&store="+params[0]+"&partNumber="+params[1]+"&plan=unlocked"
```

通过打log的方式得知，最终的url为:

```text
https://reserve-prime.apple.com/CN/zh_CN/reserve/A?quantity=1&anchor-store=R390&store=R390&partNumber=MGL93CH&plan=unlocked
```

但是访问此地址，无论怎么样都无法进行到达**确认预约页面**，会直接跳转到首页。但是手动在**预约页面**进行手动选择时，发现是可以跳转到 **确认预约页面**的。

通过抓包发现在预约 12pro 的页面中点击提交，其跳转的地址如下:

```
https://reserve-prime.apple.com/CN/zh_CN/reserve/A?color=海蓝色&capacity=128GB&quantity=1&anchor-store=R644&store=R644&partNumber=MGLD3CH/A&channel=&sourceID=&iUID=&iuToken=&iUP=N&appleCare=&rv=&path=&plan=unlocked
```

**Comment by hteen** [comment]
@BlackHole1 
链接中参数 `partNumber` 错误, 应该是 `MGL93CH/A`, 你这里是 `MGL93CH`

我本地测试没重现你这个情况, release页面下载最新包呢

**Comment by BlackHole1** [comment]
@hteen 那个地址是我复制时少复制了一位，不过问题还是存在的

**Comment by BlackHole1** [comment]
通过抓包发现，12pro的地址比12多了很多的参数的

**Comment by BlackHole1** [comment]
稍等，我提个PR

**Comment by lucien116** [comment]
> @BlackHole1
> 链接中参数 `partNumber` 错误, 应该是 `MGL93CH/A`, 你这里是 `MGL93CH`
> 
> 我本地测试没重现你这个情况, release页面下载最新包呢

我也发现好像确实存在这个问题，当选择的型号有货了自动打开的浏览器页面直接就到了主页去了，没有到预约的页面

**Comment by BlackHole1** [comment]
经过实测，发现地址是动态的，有时是前者，有时是后者
