### ISSUE TITLE
澳門上新了

### ISSUE THREAD

**Issue by tonihwang1995** [hteen/apple-store-helper#36]
大佬可以更新澳門接口啦

**Comment by hteen** [comment]
#37

**Comment by chris-choy** [comment]
> 今年其他的确都修改了预约流程, 澳门却没有修改维持去年的逻辑, 所以暂时做不到统一处理, 需要澳门地区用户大, 后期可以追究一个专属版本

你好，其实如果这样的话，直接在去年的基础上把新的机型添加上去是不是就可以用了？

**Comment by hteen** [comment]
> > 今年其他的确都修改了预约流程, 澳门却没有修改维持去年的逻辑, 所以暂时做不到统一处理, 需要澳门地区用户大, 后期可以追究一个专属版本
> 
> 你好，其实如果这样的话，直接在去年的基础上把新的机型添加上去是不是就可以用了？

是这样, 然后库存地址也需要修改

**Comment by evangeline00000** [comment]
大佬可以更新澳門接口嗎?

**Comment by mrlism888** [comment]
大佬，是否更新下澳门的

**Comment by henryhu1998** [comment]
dalao 

> 今年其他的确都修改了预约流程, 澳门却没有修改维持去年的逻辑, 所以暂时做不到统一处理, 需要澳门地区用户大, 后期可以追究一个专属版本

大佬能不能加个日本
