### ISSUE TITLE
14要出来了，求大佬更新

### ISSUE THREAD

**Issue by chenmeinanna** [hteen/apple-store-helper#50]
14要出来了，求大佬更新

**Comment by zy84338719** [comment]
已经增加iphone 14 系列  [#52 ](https://github.com/hteen/apple-store-helper/pull/52)

**Comment by htanx** [comment]
@zy84338719 大佬怎么用啊

**Comment by Alastor-Z** [comment]
为啥我每次刚运行程序就显示有货，但是实际上没货啊

**Comment by Leung1106** [comment]
> 



> 已经增加了iphone 14 系列 [#52](https://github.com/hteen/apple-store-helper/pull/52)

为什么没货他还继续跳转噢

**Comment by hteen** [comment]
已更新 14 系列
