### ISSUE TITLE
M1 mac mini 提示已损坏

### ISSUE THREAD

**Issue by YangHanqing** [hteen/apple-store-helper#54]
M1 mac mini 提示已损坏

**Comment by hteen** [comment]
> M1 mac mini 提示已损坏

尝试直接 go run main.go

**Comment by igarashikenshin** [comment]
绕过签名即可

**Comment by YangHanqing** [comment]
感谢，控制台输入下面的指令，就可以用了

sudo spctl --master-disable

**Comment by hteen** [comment]
Duplicate of #57 #56 #58
