### ISSUE TITLE
darwin-amd64 unzip后是arm64的，打包错了

### ISSUE THREAD

**Issue by igarashikenshin** [hteen/apple-store-helper#56]

**Comment by hteen** [comment]
的确是打的 amd64, 是不是损坏了?

**Comment by igarashikenshin** [comment]
Intel Mac无法运行😂
损坏问题绕一下签名就行

**Comment by charley008** [comment]
同样 intel 到mac 无法运行

**Comment by xuechuankeji** [comment]
大佬，能做全自动的吗？怎么联系你，wx或者dianbao

**Comment by GrantFung** [comment]
大佬，请问怎么绕过签名，隐私通用里面任何来源已经点开了还是提示损坏

**Comment by hteen** [comment]
```shell 
sudo xattr -rd com.apple.quarantine /Applications/xxxxxx.app
```

<img width="718" alt="image" src="https://user-images.githubusercontent.com/8476546/189510905-31382e7d-344d-47a1-866b-a4c98039ebe3.png">

#58 #57 #54
