### ISSUE TITLE
能否有日志显示

### ISSUE THREAD

**Issue by charley008** [hteen/apple-store-helper#59]
昨晚挂机一天。今早发现 有显示有货。已经错过了时机，但是不懂具体什么时候发生的事。要是有日志 就好点，至少能看看啥时间段容易抢到

**Comment by swzsweet** [comment]
> 昨晚挂机一天。今早发现 有显示有货。已经错过了时机，但是不懂具体什么时候发生的事。要是有日志 就好点，至少能看看啥时间段容易抢到

我看过放货规律，可以说是毫无规律，所以日志需求暂时没啥用

**Comment by youngbeway1217** [comment]
> 昨晚挂机一天。今早发现 有显示有货。已经错过了时机，但是不懂具体什么时候发生的事。要是有日志 就好点，至少能看看啥时间段容易抢到

我加上日志了，有货的话。

**Comment by zsnzzg** [comment]
> > 昨晚挂机一天。今早发现 有显示有货。已经错过了时机，但是不懂具体什么时候发生的事。要是有日志 就好点，至少能看看啥时间段容易抢到
> 
> 我加上日志了，有货的话。

哪里呀
