### ISSUE TITLE
刷一段时候后ip会被封

### ISSUE THREAD

**Issue by miaowh** [hteen/apple-store-helper#62]
被封之后，即使官网有货也查询不到

**Comment by jasoft** [comment]
是的，我刚也被封了。相同ip频繁访问页面，触发防火墙规则很容易被拦掉。

**Comment by eaglexxxm** [comment]
如果能查看是否被封？

**Comment by miaowh** [comment]
> 如果能查看是否被封？

无法访问购物袋

**Comment by cuiks** [comment]
> 被封之后，即使官网有货也查询不到

我是通过使用代理IP解决的。请求库存接口的时候使用本机的代理IP

**Comment by helloBeren** [comment]
我也遇到了这个问题，请问大家是被封一段时间还是永久封？我目前是如果被封就断开pppoe拨号然后再拨通，就可以换个ip继续监控了。

**Comment by helloBeren** [comment]
> 我也遇到了这个问题，请问大家是被封一段时间还是永久封？我目前是如果被封就断开pppoe拨号然后再拨通，就可以换个ip继续监控了。

自己回复，大概会被ban两个小时左右
