### ISSUE TITLE
软件无法在windows7 下面运行

### ISSUE THREAD

**Issue by jfhufhf** [hteen/apple-store-helper#66]
试了一下 用了两个windows7的系统运行这个软件 均无反应,windows8以上正常.
查了一下fyne UI的提示 
https://github.com/fyne-io/fyne/issues/410
不知道是否能修复这个问题 谢谢.

**Comment by chekun** [comment]
和windows7无关，和虚拟机有关，你下载一个 mesa3d 的dll 和exe放一起就可以了，下载地址：

https://fdossena.com/?p=mesa/index.frag
