### ISSUE TITLE
iphone15系列还会更新吗

### ISSUE THREAD

**Issue by Bluryah** [hteen/apple-store-helper#72]
RT

**Comment by zhangyanyue** [comment]
可以自己改改

**Comment by Bluryah** [comment]
> 可以自己改改

有点小白这个该怎么改呢

**Comment by RayJason** [comment]
提了个 PR ：https://github.com/hteen/apple-store-helper/pull/75

**Comment by azxcvjj** [comment]
> 提了个 PR ：#75

大佬可以打包下吗

**Comment by RayJason** [comment]
> > 提了个 PR ：#75
> 
> 大佬可以打包下吗

https://github.com/RayJason/apple-store-helper/releases/tag/1.5.0

**Comment by azxcvjj** [comment]
> > > 提了个 PR ：#75
> 
> > 
> 
> > 大佬可以打包下吗
> 
> 
> 
> https://github.com/RayJason/apple-store-helper/releases/tag/1.5.0

谢谢🙏

**Comment by 52assert** [comment]
> > > 提了个 PR ：#75
> > 
> > 
> > 大佬可以资源下吗
> 
> https://github.com/RayJason/apple-store-helper/releases/tag/1.5.0

<img width="875" alt="image" src="https://github.com/hteen/apple-store-helper/assets/63569490/f05d029c-2d3f-42cb-b43d-6ed3ae49df07">
你好，想问一下打包报这个错是为什么呀

**Comment by 52assert** [comment]
> 提了个 PR ：#75

还有这个是不是应该加一下 ProductsJson 呀

**Comment by RayJason** [comment]
> > 提了个 PR ：#75
> 
> 
> 
> 还有这个是不是应该加一下 ProductsJson 呀

model 改过了呀

**Comment by 52assert** [comment]
> > > 提了个 PR ：#75
> > 
> > 
> > 还有这个是不是应该加一下 ProductsJson 呀
> 
> model 改过了呀

对的 改动太大了被折叠没注意

**Comment by 52assert** [comment]
> > > 提了个 PR ：#75
> > 
> > 
> > 还有这个是不是应该加一下 ProductsJson 呀
> 
> model 改过了呀

可以帮忙看下上面打包那个错误可能是因为什么吗，谢谢

**Comment by 52assert** [comment]
> > > > 提了个 PR ：#75
> > > 
> > > 
> > > 还有这个是不是应该加一下 ProductsJson 呀
> > 
> > 
> > model 改过了呀
> 
> 可以帮忙看下上面打包那个错误可能是因为什么吗，谢谢

go version go1.19.3 darwin/arm64

**Comment by RayJason** [comment]
> > > > 提了个 PR ：#75
> > > 
> > > 
> > > 大佬可以资源下吗
> > 
> > 
> > https://github.com/RayJason/apple-store-helper/releases/tag/1.5.0
> 
> <img alt="image" width="875" src="https://user-images.githubusercontent.com/63569490/268479884-f05d029c-2d3f-42cb-b43d-6ed3ae49df07.png"> 你好，想问一下打包报这个错是为什么呀

我在我的pr里更新了 README.md，用 install 重装一下 fyne，并且确定环境变量路径正确，再重试。我不确定这里找不到的二进制文件是哪个。

**Comment by 52assert** [comment]
> > > > > 提了个 PR ：#75
> > > > 
> > > > 
> > > > 大佬可以资源下吗
> > > 
> > > 
> > > https://github.com/RayJason/apple-store-helper/releases/tag/1.5.0
> > 
> > 
> > <img alt="image" width="875" src="https://user-images.githubusercontent.com/63569490/268479884-f05d029c-2d3f-42cb-b43d-6ed3ae49df07.png"> 你好，想问一下打包报这个错是为什么呀
> 
> 我在我的pr里更新了 README.md，用 install 重装一下 fyne，并且确定环境变量路径正确，再重试。我不确定这里找不到的二进制文件是哪个。

没错，我是按照新的readme来的，还是不行

- [ ]

**Comment by TienSato** [comment]
can you package it for mac os and windows Version 1.5.1

**Comment by TienSato** [comment]
I think an English version would be great

**Comment by RayJason** [comment]
> > > > > > 提了个 PR ：#75
> > > > > 
> > > > > 
> > > > > 大佬可以资源下吗
> > > > 
> > > > 
> > > > https://github.com/RayJason/apple-store-helper/releases/tag/1.5.0
> > > 
> > > 
> > > <img alt="image" width="875" src="https://user-images.githubusercontent.com/63569490/268479884-f05d029c-2d3f-42cb-b43d-6ed3ae49df07.png"> 你好，想问一下打包报这个错是为什么呀
> > 
> > 
> > 我在我的pr里更新了 README.md，用 install 重装一下 fyne，并且确定环境变量路径正确，再重试。我不确定这里找不到的二进制文件是哪个。
> 
> 没错，我是按照新的readme来的，还是不行
> 
> * [ ]

我本地没遇到过这个问题，我觉得应该是你环境安装的问题。你可以直接下载最新版，我加了缓存：
https://github.com/RayJason/apple-store-helper/releases/tag/1.5.1

**Comment by 52assert** [comment]
> > > > > > > 提了个 PR ：#75
> > > > > > 
> > > > > > 
> > > > > > 大佬可以资源下吗
> > > > > 
> > > > > 
> > > > > https://github.com/RayJason/apple-store-helper/releases/tag/1.5.0
> > > > 
> > > > 
> > > > <img alt="image" width="875" src="https://user-images.githubusercontent.com/63569490/268479884-f05d029c-2d3f-42cb-b43d-6ed3ae49df07.png"> 你好，想问一下打包报这个错是为什么呀
> > > 
> > > 
> > > 我在我的pr里更新了 README.md，用 install 重装一下 fyne，并且确定环境变量路径正确，再重试。我不确定这里找不到的二进制文件是哪个。
> > 
> > 
> > 没错，我是按照新的readme来的，还是不行
> > 
> > * [ ]
> 
> 我本地没遇到过这个问题，我觉得应该是你环境安装的问题。你可以直接下载最新版，我加了缓存： https://github.com/RayJason/apple-store-helper/releases/tag/1.5.1

感谢感谢，主要也是想研究研究哈哈
