### ISSUE TITLE
can you package it for mac os and windows

### ISSUE THREAD

**Issue by TienSato** [hteen/apple-store-helper#77]
can you package it for mac os and windows

**Comment by RayJason** [comment]
I've updated the caching feature and it hasn't been merged in yet, you can download the latest version here: 
https://github.com/RayJason/apple-store-helper/releases/tag/1.5.1

**Comment by TienSato** [comment]
Can you help me a little? If there is an English version that would be
great, the Thai region seems to ship very quickly.

**Comment by RayJason** [comment]
> Can you help me a little? If there is an English version that would be great, the Thai region seems to ship very quickly.

Are you based in Thailand? This program currently only supports China, Singapore and Japan. Maybe support Thailand in the future.
English version is indeed a good idea. Possibility to add a button to switch languages. I'll take care of that need while I'm poking around at work with ChatGPT code interpreter.

**Comment by TienSato** [comment]
Can this software be ordered and received at the apple store?, I am in
Singapore and want to order and receive goods at the apple store

**Comment by RayJason** [comment]
> Can this software be ordered and received at the apple store?, I am in Singapore and want to order and receive goods at the apple store

This tool can help u listen for inventory in the Apple Store offline store. If it's in stock, it will open your browser to a shopping cart page. The subsequent ordering process needs to be done by yourself.

**Comment by TienSato** [comment]
Thank you for creating such great software. I and many people are looking
forward to the English version. It's been another month of eating instant
noodles 🌚🌚

**Comment by RayJason** [comment]
> Thank you for creating such great software. I and many people are looking forward to the English version. It's been another month of eating instant noodles 🌚🌚

lol, I'm not the author. It just so happens that I wanted to buy 15 series, so I'm participating in the contribution. I'll try to support multiple languages.

**Comment by RayJason** [comment]
I build a English version for Windows. You can try this version first. Download `windows-amd64-en.exe.zip` then unzip.
https://github.com/RayJason/apple-store-helper/releases/tag/1.5.1

I created a branch at the same time and translated the README with ChatGPT.  
https://github.com/RayJason/apple-store-helper/blob/feat/i18n/README-en.md

**Comment by TienSato** [comment]
That's great, thank you very much boss
