### ISSUE TITLE
通知里面建议加时效性通知，可在专注状态下显示通知。

### ISSUE THREAD

**Issue by mifengwei** [hteen/apple-store-helper#88]
// 设置时效性通知
https://api.day.app/yourkey/时效性通知?level=timeSensitive

// 可选参数值
// active：不设置时的默认值，系统会立即亮屏显示通知。
// timeSensitive：时效性通知，可在专注状态下显示通知。
// passive：仅将通知添加到通知列表，不会亮屏提醒

apiUrl := fmt.Sprintf("%s/%s/%s?level=timeSensitive&url=%s", strings.TrimRight(s.BarkNotifyUrl, "/"), title, content, bagUrl)

**Comment by yyyaxuan** [comment]
我自己下载代码尝试改了一下，可以做到时效性通知和改铃声。大概就是把通知测试和正式通知的“SendPushNotificationByBark”后面括号里最后一段替换为“&sound=minuet&level=timeSensiti”。minuet为铃声，app内可以自己选择想要的铃声。
