### ISSUE TITLE
请求增加澳门直营店预约

### ISSUE THREAD

**Issue by aw0o** [hteen/apple-store-helper#9]
如题~谢谢大佬~

**Comment by deepfish** [comment]
我也是需要澳門的預約，不知道能否添加呢？

**Comment by hteen** [comment]
@deepfish @aw0o 

澳门地区 

[darwin-amd64.zip](https://github.com/hteen/apple-store-helper/files/5552664/darwin-amd64.zip)
[linux-amd64.zip](https://github.com/hteen/apple-store-helper/files/5552665/linux-amd64.zip)
[windows-386.zip](https://github.com/hteen/apple-store-helper/files/5552666/windows-386.zip)
[windows-amd64.zip](https://github.com/hteen/apple-store-helper/files/5552667/windows-amd64.zip)
