### ISSUE TITLE
找到货后，“开始/暂停” 按钮有概率消失

### ISSUE THREAD

**Issue by troy351** [hteen/apple-store-helper#95]
<img width="1000" alt="image" src="https://github.com/user-attachments/assets/ee2355f1-db51-4467-bd44-d9731529c846">

并希望增加一个持续寻找功能，即找到货后不自动暂停。
因为每次放货量都很少，点进去就没了，又得重新点“开始”，还不如一直找着呢。
不过需要注意的是：若某一款SKU已找到，需要防止重复弹出找到消息，直到变为无货

**Comment by ming019** [comment]
Agree that should be infinite loop instead.

**Comment by BigPig02** [comment]
> <img alt="image" width="1000" src="https://private-user-images.githubusercontent.com/8372385/367494147-ee2355f1-db51-4467-bd44-d9731529c846.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwOTI4NTIsIm5iZiI6MTcyNzA5MjU1MiwicGF0aCI6Ii84MzcyMzg1LzM2NzQ5NDE0Ny1lZTIzNTVmMS1kYjUxLTQ0NjctYmQ0NC1kOTczMTUyOWM4NDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjNUMTE1NTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWVlMThlYmQwYTg5ZjFkODNjYjU4YWVjMGY2M2JjMzQ1OWUzMDYyOGFmNDViZGY5MzI3NTc2ZDQxYmEwNGMwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.zaf6lqLZp1_RnTMcZFFy9f8zsvZSbuoOeNCFNFfP29E">
> 并希望增加一个持续寻找功能，即找到货后不自动暂停。 因为每次放货量都很少，点进去就没了，又得重新点“开始”，还不如一直找着呢。 不过需要注意的是：若某一款SKU已找到，需要防止重复弹出找到消息，直到变为无货

希望有这个功能
