### ISSUE TITLE
请问我下载1.6.1打开出现以下问题

### ISSUE THREAD

**Issue by simonwellchang** [hteen/apple-store-helper#96]
请问我下载1.6.1打开出现以下问题？再麻烦协助一下，谢谢

![SCR-20240916-itpa](https://github.com/user-attachments/assets/89a1b15b-1c05-48a5-be51-9387a2c27e4d)

**Comment by simonwellchang** [comment]
sudo xattr -d com.apple.quarantine /Applications/apple-store-helper.app
 
 出現：
<img width="127" alt="SCR-20240916-iycg" src="https://github.com/user-attachments/assets/570231d2-84ff-4dbe-bffd-ac20240b0bb5">

**Comment by hteen** [comment]
试试 darwin-amd64

**Comment by simonwellchang** [comment]
> 试试 darwin-amd64

可以喔～感谢
